DATA ANALYSIS

In [11]:
import os
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    GITHUB_USER = "SinghSahiljit44"  # Es. sahiljit
    REPO_NAME = "Weather_forecasting"
    REPO_URL = f"https://github.com/{GITHUB_USER}/{REPO_NAME}.git"

    # Clona la repository se non è già stata clonata nella sessione
    if not os.path.exists(REPO_NAME):
        !git clone {REPO_URL}

    # Cambia la directory di lavoro nella root del progetto
    os.chdir(REPO_NAME)
    
    # Installa le dipendenze necessarie nell'ambiente di Colab
    !pip install -q -r requirements.txt
    
    PROJECT_ROOT = Path.cwd()
else:
    # --- CONFIGURAZIONE LOCALE  ---
    PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
    os.chdir(PROJECT_ROOT)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(f" [OK] Ambiente rilevato: {'Google Colab' if IN_COLAB else 'Locale'}")
print(f" [OK] Directory di lavoro impostata a: {Path.cwd()}")

 [OK] Ambiente rilevato: Locale
 [OK] Directory di lavoro impostata a: c:\Users\sahil\GitHub\Weather_forecasting

In [18]:
from src.data.dataset import load_hourly

# Carica il dataframe con i dati orari
df_hourly = load_hourly()

# Mostra le prime 48 ore (i primi due giorni completi)
df_hourly.head(48)

                          t2m       skt      stl1      stl2       stl3       stl4     swvl1     swvl2     swvl3     swvl4       pev         e        tp
time
1990-01-01 00:00:00  3.691919  2.302026  4.594263  6.877100  10.465723  16.038232  0.435532  0.417847  0.331802  0.314011 -0.877649 -0.366595  0.556895
1990-01-01 01:00:00  3.363550  1.943262  4.407495  6.798730  10.456079  16.034937  0.435349  0.417847  0.331833  0.314011  0.002131  0.002133  0.005156
1990-01-01 02:00:00  2.892114  1.389429  4.137476  6.712305  10.446436  16.031641  0.435135  0.417862  0.331848  0.314011  0.004981  0.004981  0.005418
1990-01-01 03:00:00  3.162744  1.776025  4.190332  6.631738  10.436792  16.028345  0.434967  0.417862  0.331863  0.314011  0.007249  0.007248  0.007827
1990-01-01 04:00:00  3.888330  2.631738  4.450952  6.572656  10.428979  16.025049  0.435364  0.417877  0.331879  0.314011  0.008661  0.008662  0.062440
1990-01-01 05:00:00  4.498682  3.321436  4.708276  6.531396  10.419092  16.021753  0.437424  0.417892  0.331894  0.314011  0.009891  0.009893  0.238009
1990-01-01 06:00:00  5.317163  4.297266  5.101099  6.513818  10.409204  16.016626  0.440689  0.417938  0.331909  0.314011  0.008993  0.008994  0.492454
1990-01-01 07:00:00  5.892480  4.971582  5.426172  6.513818  10.399194  16.013330  0.442307  0.417984  0.331940  0.314011  0.007238  0.007237  0.633188
1990-01-01 08:00:00  6.500513  5.696436  5.792871  6.535913  10.389185  16.010034  0.443939  0.418060  0.331955  0.314011  0.003539  0.003539  0.779666
1990-01-01 09:00:00  7.229028  6.668604  6.279077  6.579858  10.381128  16.006738  0.445236  0.418121  0.331970  0.314011 -0.007201 -0.007197  0.913106
1990-01-01 10:00:00  7.759302  7.454370  6.726465  6.645532  10.370996  16.003442  0.445969  0.418213  0.332001  0.314011 -0.025887 -0.025887  1.014382
1990-01-01 11:00:00  8.386011  8.407983  7.263574  6.736719  10.362817  16.000146  0.446060  0.418304  0.332016  0.314011 -0.062127 -0.062125  1.084879
1990-01-01 12:00:00  8.727441  8.691431  7.554102  6.835840  10.356592  15.996851  0.446121  0.418381  0.332031  0.314011 -0.108350 -0.107804  1.152858
1990-01-01 13:00:00  8.963403  8.932886  7.795801  6.940942  10.348413  15.993555  0.446243  0.418472  0.332062  0.314011 -0.156730 -0.153353  1.226768
1990-01-01 14:00:00  8.815332  8.694727  7.816309  7.040186  10.342065  15.990259  0.446793  0.418564  0.332077  0.314011 -0.189804 -0.183120  1.347810
1990-01-01 15:00:00  8.544092  8.279932  7.730981  7.127588  10.335718  15.986963  0.448273  0.418671  0.332092  0.314011 -0.207447 -0.200128  1.516461
1990-01-01 16:00:00  8.074365  7.604395  7.498438  7.197412  10.329370  15.983667  0.449951  0.418777  0.332123  0.314011 -0.211053 -0.203732  1.677737
1990-01-01 17:00:00  7.710229  7.118555  7.300562  7.251245  10.322900  15.980371  0.450928  0.418900  0.332138  0.314011 -0.211120 -0.203805  1.789302
1990-01-01 18:00:00  7.515405  6.864526  7.176416  7.293359  10.318506  15.977197  0.451721  0.419037  0.332153  0.314011 -0.210807 -0.203487  1.888007
1990-01-01 19:00:00  7.561426  6.931787  7.172876  7.332788  10.313989  15.971948  0.455353  0.419205  0.332169  0.314011 -0.210389 -0.203066  2.194315
1990-01-01 20:00:00  7.373071  6.716089  7.082910  7.366479  10.307397  15.968652  0.458618  0.419403  0.332184  0.314011 -0.208467 -0.201151  2.484113
1990-01-01 21:00:00  7.190088  6.514551  6.994653  7.390039  10.302759  15.965356  0.461914  0.419678  0.332214  0.314011 -0.206105 -0.198791  2.784073
1990-01-01 22:00:00  7.000391  6.481592  6.964868  7.411401  10.297388  15.962061  0.466003  0.419983  0.332230  0.314011 -0.204451 -0.197131  3.155559
1990-01-01 23:00:00  6.964624  6.509302  6.966333  7.430688  10.292749  15.958765  0.470840  0.420410  0.332260  0.314011 -0.202738 -0.195418  3.600776
1990-01-02 00:00:00  6.798975  6.350977  6.903833  7.445825  10.288232  15.955591  0.476471  0.420959  0.332275  0.314011 -0.200681 -0.193361  4.132360
1990-01-02 01:00:00  6.660059  6.200708  6.839502  7.457056  10.283594  15.952295  0.482269  0.421707  0.332306  0.314011  0.001967  0.001967  0.585480
1990-01-02 02:00:00  6.626489  6.198022  6.828394  7.464624  10.280908  15.948999  0.485703  0.422714  0.332321  0.314011  0.003411  0.003411  1.057805
1990-01-02 03:00:00  6.592920  6.152002  6.804224  7.472070  10.275659  15.945703  0.487732  0.423874  0.332336  0.314011  0.004368  0.004367  1.464661
1990-01-02 04:00:00  6.554956  6.068140  6.769189  7.475854  10.270898  15.940454  0.489944  0.425140  0.332367  0.314011  0.005599  0.005599  1.908310
1990-01-02 05:00:00  6.552881  6.044336  6.752344  7.477930  10.266138  15.937280  0.490433  0.426514  0.332397  0.314011  0.006825  0.006826  2.253354
1990-01-02 06:00:00  6.427148  5.851099  6.673364  7.476465  10.263330  15.933984  0.489319  0.427856  0.332428  0.314011  0.008259  0.008259  2.477638
1990-01-02 07:00:00  6.879907  6.081812  6.745874  7.479150  10.258447  15.930688  0.489120  0.429077  0.332458  0.314011  0.009287  0.009283  2.742700
1990-01-02 08:00:00  7.882837  7.257227  7.207178  7.507471  10.253564  15.927393  0.487488  0.430222  0.332474  0.314011  0.007443  0.007444  2.893887
1990-01-02 09:00:00  8.721582  8.635645  7.827051  7.567407  10.250635  15.924097  0.486649  0.431244  0.332520  0.314011 -0.007641 -0.007640  3.088906
1990-01-02 10:00:00  9.209009  9.548975  8.357202  7.651270  10.245630  15.920801  0.487701  0.432205  0.332550  0.314011 -0.061940 -0.061941  3.448144
1990-01-02 11:00:00  9.658350  9.865991  8.682153  7.748804  10.242700  15.917627  0.488510  0.433228  0.332581  0.314011 -0.148326 -0.148244  3.831759
1990-01-02 12:00:00  9.501489  9.510400  8.682764  7.838647  10.241602  15.912378  0.489517  0.434265  0.332611  0.314011 -0.203405 -0.203323  4.206613
1990-01-02 13:00:00  9.410913  9.403589  8.718164  7.924585  10.239160  15.909082  0.488907  0.435333  0.332642  0.314011 -0.253685 -0.253598  4.464850
1990-01-02 14:00:00  9.119653  9.028223  8.616357  7.998926  10.238062  15.905786  0.487976  0.436310  0.332687  0.314011 -0.287078 -0.286997  4.668996
1990-01-02 15:00:00  8.710962  8.478784  8.410547  8.055200  10.236963  15.902490  0.487625  0.437241  0.332718  0.314011 -0.305273 -0.305191  4.886240
1990-01-02 16:00:00  8.329370  7.974268  8.190576  8.096094  10.235986  15.899194  0.487122  0.438095  0.332764  0.314011 -0.313759 -0.313675  5.073476
1990-01-02 17:00:00  8.036401  7.571802  7.995386  8.123071  10.234888  15.896021  0.485962  0.438919  0.332809  0.314011 -0.318229 -0.318148  5.200583
1990-01-02 18:00:00  7.908594  7.401758  7.887598  8.143945  10.231836  15.892725  0.484268  0.439651  0.332855  0.314011 -0.324026 -0.323937  5.271423
1990-01-02 19:00:00  7.417749  6.840845  7.640527  8.148950  10.230737  15.889429  0.482315  0.440277  0.332886  0.314011 -0.321575 -0.321492  5.296188
1990-01-02 20:00:00  7.258936  6.613916  7.500635  8.143945  10.229639  15.886133  0.480545  0.440811  0.332932  0.314011 -0.319898 -0.319812  5.315232
1990-01-02 21:00:00  7.223657  6.599023  7.446313  8.138574  10.228540  15.882837  0.478851  0.441269  0.332977  0.314011 -0.320800 -0.320721  5.326780
1990-01-02 22:00:00  6.948511  6.267847  7.288232  8.123315  10.227319  15.877588  0.477310  0.441666  0.333023  0.314011 -0.317223 -0.317141  5.331787
1990-01-02 23:00:00  6.942285  6.223291  7.227808  8.105981  10.226099  15.874292  0.475861  0.442001  0.333069  0.314011 -0.317231 -0.317149  5.334171

In [23]:
from src.data.preprocessing import load_daily

# Carica il dataframe con i dati giornalieri
df_daily = load_daily()

# Mostra i primi 2 giorni
df_daily.tail(64)

             t2m_mean    t2m_min    t2m_max      tp_mm      e_mm    pev_mm   skt_mean  stl1_mean  stl2_mean  stl3_mean  stl4_mean  swvl1_mean  swvl2_mean  swvl3_mean  swvl4_mean
date
2025-10-28  15.391692  11.064111  20.579858   0.008285 -1.176426 -2.936468  14.751306  16.577412  17.931996  19.612299  23.352533    0.397895    0.399992    0.291099    0.303864
2025-10-29  15.801696  10.427759  22.875879   0.000852 -1.187338 -3.281467  14.802357  16.004917  16.932835  19.500869  23.299244    0.390474    0.395995    0.291378    0.303855
2025-10-30  16.480147  10.128442  23.030542   0.004101 -0.978252 -3.074855  15.451049  16.215311  16.816797  19.359761  23.244953    0.383889    0.392291    0.291619    0.303848
2025-10-31  17.364824  13.114526  22.882349   0.237912 -0.963668 -2.333701  16.850626  17.265436  17.354801  19.258066  23.189940    0.378935    0.388842    0.291822    0.303840
2025-11-01  17.485546  14.125757  22.637720   0.049400 -0.995166 -2.349131  17.570871  17.980422  18.026473  19.237451  23.135273    0.375310    0.385604    0.291998    0.303833
2025-11-02  17.522699  11.873560  23.989038   0.004727 -1.098630 -3.155626  16.721765  17.440225  17.861312  19.239842  23.080596    0.370003    0.382349    0.292146    0.303827
2025-11-03  17.048069  14.282861  20.977563   6.859422 -1.037366 -2.039969  16.420597  17.335135  17.982797  19.245950  23.026529    0.397647    0.380247    0.292280    0.303818
2025-11-04  14.051065  10.934961  17.182520   0.003952 -1.083335 -4.050322  13.653314  15.560312  17.136382  19.208139  22.973484    0.430777    0.383219    0.292435    0.303818
2025-11-05  12.775517   8.546045  18.201318   0.000858 -0.895934 -2.656035  12.444879  14.255919  15.798339  19.044132  22.920338    0.414689    0.383489    0.292592    0.303818
2025-11-06  12.309206   6.048975  18.513940   0.000435 -0.866396 -2.001181  11.683399  13.514347  15.058639  18.802281  22.864267    0.404311    0.382339    0.292740    0.303808
2025-11-07  12.472498   5.707178  18.344507   0.791982 -0.791582 -1.990415  12.361566  13.440042  14.475351  18.522643  22.804951    0.397397    0.380713    0.292880    0.303802
2025-11-08  13.924488  12.059839  16.873926   0.539434 -0.683394 -1.471229  13.309618  14.264330  15.106241  18.298115  22.743661    0.399904    0.379570    0.293022    0.303802
2025-11-09  14.090260  11.277490  17.016260  12.544256 -0.809966 -1.163654  13.568272  14.283065  15.004739  18.119455  22.679422    0.456359    0.383854    0.293187    0.303802
2025-11-10  13.940566  10.113550  17.679834   3.445855 -1.398567 -3.318474  13.712938  14.768864  15.467798  17.981449  22.614842    0.474192    0.419259    0.293600    0.303794
2025-11-11  11.715448   6.476709  18.406030   0.001720 -1.115642 -2.637558  11.040903  13.056594  14.681980  17.837503  22.548649    0.445179    0.422897    0.294328    0.303787
2025-11-12  11.323480   4.201318  19.517053   0.000852 -1.026606 -2.077289  10.158617  11.994760  13.578505  17.601836  22.481302    0.432002    0.419909    0.295014    0.303787
2025-11-13  11.827163   4.772852  20.203271   0.000000 -0.895523 -1.804546  10.500080  11.981482  13.228174  17.326110  22.410705    0.423097    0.416267    0.295612    0.303787
2025-11-14  11.805371   5.562158  20.008813   0.001710 -0.842256 -1.793347  10.513165  11.947026  13.125452  17.068628  22.337895    0.416178    0.412671    0.296135    0.303780
2025-11-15  12.089677   5.091211  20.087793   0.000426 -0.755180 -1.600400  10.236294  11.590969  12.823831  16.824172  22.261906    0.410469    0.409265    0.296592    0.303772
2025-11-16  14.821334   8.428125  22.291284   0.000852 -0.783978 -1.849912  12.321644  12.810871  13.180816  16.609069  22.184259    0.405329    0.406001    0.296990    0.303772
2025-11-17  16.165013  12.325098  21.980127   0.604990 -0.720966 -2.329692  14.436614  14.503076  14.380258  16.513320  22.104949    0.400299    0.402859    0.297341    0.303764
2025-11-18  13.764520  12.032007  16.033960  17.916376 -0.311222 -0.329971  12.948462  13.786045  14.613529  16.514169  22.026270    0.455142    0.421105    0.297798    0.303757
2025-11-19  12.411656  10.597192  14.415674   0.202024 -0.417611 -0.824474  11.949462  13.189091  14.286167  16.486698  21.948180    0.461075    0.455719    0.299816    0.303757
2025-11-20  13.239648   8.138574  18.915796   2.965115 -0.958536 -2.336651  12.077188  12.883178  13.535593  16.383615  21.870828    0.455223    0.449570    0.301870    0.303757
2025-11-21  10.390716   6.146387  13.393457   6.591368 -0.743866 -0.863105   9.114969  11.434529  13.400079  16.286076  21.792744    0.486138    0.454038    0.303652    0.303757
2025-11-22   9.145507   6.601587  12.805444   0.409853 -0.827804 -2.121195   8.040623   9.967925  11.752171  16.061355  21.713617    0.478228    0.463472    0.306346    0.303757
2025-11-23   7.346114   4.099512  11.619165   0.031590 -0.733262 -2.154157   6.603352   8.884887  10.924107  15.747242  21.631123    0.462388    0.457133    0.308900    0.303757
2025-11-24  10.231739   3.742700  15.718164   3.681332 -0.700636 -1.471817   8.549590   9.274047  10.158289  15.373392  21.544458    0.464595    0.451297    0.310860    0.303757
2025-11-25  13.808745  11.444727  17.277979  16.492300 -1.039552 -1.345038  12.454319  12.319564  12.087432  15.139154  21.455103    0.483559    0.464788    0.312904    0.303757
2025-11-26  11.675429   7.462671  15.533594   6.453753 -0.852821 -1.809895  10.520344  11.685464  12.539540  15.067550  21.363794    0.450265    0.476251    0.328818    0.303757
2025-11-27   9.924178   8.690088  12.655908   3.398166 -0.941116 -1.479395   9.759241  11.129154  12.257832  15.000116  21.272719    0.492474    0.475464    0.333019    0.303757
2025-11-28   9.288197   8.191064  10.511987   4.835629 -1.192685 -1.555622   8.667907  10.137160  11.565154  14.883722  21.181558    0.496002    0.478224    0.337247    0.303757
2025-11-29   9.375899   5.799707  12.245142   0.096494 -0.596172 -1.987830   8.835703  10.125907  11.264444  14.714283  21.089319    0.478495    0.474771    0.341625    0.303757
2025-11-30   8.388137   3.087305  14.689966   0.000164 -0.695740 -1.367867   7.169710   9.057957  10.632730  14.521117  20.995213    0.466823    0.465672    0.344589    0.303757
2025-12-01   8.484374   1.817285  15.051904   0.037551 -0.585834 -1.174241   7.163329   8.576054   9.899357  14.274108  20.898645    0.458912    0.458349    0.346608    0.303757
2025-12-02  10.704518   5.635889  15.134668   3.276247 -0.442166 -0.801295   8.947738   9.707651  10.375177  14.055271  20.800338    0.460616    0.452999    0.348143    0.303770
2025-12-03   9.430755   6.262354  14.283228   0.010955 -0.639144 -1.080446   8.655852   9.787724  10.678562  13.913726  20.701471    0.471120    0.454240    0.349543    0.303772
2025-12-04   9.938348   8.150903  12.161646  21.338820 -0.303198 -0.307478   8.381408   9.607512  10.772684  13.812901  20.601531    0.458138    0.476543    0.362050    0.303777
2025-12-05  10.489013   5.911035  14.377954   1.580447 -0.565073 -0.885732   9.540526   9.951570  10.410903  13.681833  20.499546    0.452377    0.467790    0.372782    0.303792
2025-12-06  10.799903   7.339258  13.637720   0.145108 -0.773732 -2.151951  10.111879  10.833732  11.350554  13.625716  20.398228    0.461921    0.461346    0.374540    0.303809
2025-12-07   9.645624   5.980615  14.385767   0.006559 -0.732368 -1.778774   8.889800  10.014317  10.945220  13.592304  20.298059    0.455042    0.456215    0.375823    0.303827
2025-12-08  10.133666   5.432275  15.051782   0.005811 -0.602921 -1.397744   9.454805  10.417790  11.115727  13.546579  20.197895    0.449352    0.451401    0.376783    0.303844
2025-12-09   8.983125   2.498438  16.785181   0.000000 -0.621986 -1.079246   7.391087   9.073551  10.472309  13.481251  20.098388    0.444948    0.447244    0.377549    0.303864
2025-12-10   8.330067   2.063867  16.282739   0.000852 -0.560654 -1.024917   6.936029   8.469761   9.817906  13.344425  19.999679    0.441074    0.443525    0.378152    0.303884
2025-12-11   8.139706   4.087793  14.777979   0.006571 -0.432510 -0.894718   7.700688   8.797774   9.747100  13.187835  19.899423    0.437756    0.440272    0.378653    0.303904
2025-12-12   8.526313   4.512354  12.693689   0.108647 -0.373479 -0.789978   8.314221   9.029815   9.767536  13.051497  19.798390    0.435356    0.437578    0.379100    0.303916
2025-12-13   9.273876   4.190576  13.409326   0.053665 -0.474641 -0.965498   9.005126   9.946044  10.587905  12.984460  19.697346    0.433814    0.435207    0.379488    0.303938
2025-12-14   7.830113   2.884180  14.268945   0.001713 -0.486381 -0.964321   6.712750   8.364409   9.811695  12.918446  19.596979    0.430911    0.432808    0.379782    0.303961
2025-12-15   7.318043   0.497217  14.145166   0.002151 -0.474902 -0.986770   5.967732   7.561461   9.020924  12.768111  19.496673    0.428051    0.430459    0.380019    0.303982
2025-12-16   9.399357   7.299219  11.723657   1.240522 -0.059579 -0.225402   7.286704   7.949055   8.827305  12.585942  19.394861    0.427731    0.428614    0.380268    0.304001
2025-12-17  11.866874   7.017480  18.544824   0.061291 -0.527549 -0.977978  10.681985  10.604410  10.288451  12.493712  19.293014    0.438892    0.427887    0.380511    0.304024
2025-12-18  10.556736   5.974512  16.470850   0.006005 -0.383906 -0.717700   8.838457   9.884879  10.660211  12.531081  19.191787    0.433626    0.427037    0.380692    0.304048
2025-12-19   9.125408   4.550684  14.938501   0.000435 -0.429768 -0.832163   7.465476   8.724359   9.866922  12.519011  19.092991    0.429495    0.425768    0.380849    0.304071
2025-12-20  10.657208   7.889185  13.778589   0.221479 -0.326535 -0.757955  10.371996  10.341084  10.336557  12.485564  18.994745    0.426851    0.424436    0.380997    0.304094
2025-12-21  10.517791   7.888818  13.845605   0.281492 -0.349469 -0.583909   9.736439  10.391700  10.891066  12.524937  18.898248    0.426677    0.423387    0.381162    0.304114
2025-12-22  10.487838   7.626733  14.274805   0.133181 -0.295882 -0.787348  10.282368  10.609280  10.887771  12.571553  18.803028    0.425735    0.422436    0.381312    0.304132
2025-12-23  11.542017   9.071069  15.171411   1.261386 -0.298997 -0.741035  11.193702  11.292139  11.304595  12.635253  18.710962    0.427642    0.421498    0.381444    0.304157
2025-12-24   9.799799   6.685938  13.856104   0.049606 -0.665329 -1.595557   7.731287   9.467752  10.881377  12.697651  18.621062    0.433057    0.421218    0.381543    0.304180
2025-12-25   9.827432   7.250146  14.055566   1.161253 -0.463853 -0.978976   7.540653   8.773706   9.873112  12.643289  18.532327    0.429829    0.420558    0.381601    0.304202
2025-12-26  10.215005   7.793481  13.276147   0.992963 -0.453901 -0.620902   9.722304  10.000218  10.249094  12.570006  18.443806    0.439650    0.420846    0.381698    0.304223
2025-12-27   9.153858   6.443262  11.193872   0.015781 -0.500434 -1.525402   8.675556   9.642191  10.467803  12.550002  18.356556    0.436629    0.421674    0.381828    0.304250
2025-12-28   7.735994   2.388330  13.415552   0.001284 -0.683187 -1.857579   7.118789   8.516621   9.714873  12.484801  18.269957    0.429790    0.421177    0.381885    0.304272
2025-12-29   7.517165   2.175928  13.133081   0.000852 -0.609646 -1.373537   5.763895   7.700311   9.291325  12.367039  18.182240    0.423934    0.419802    0.381882    0.304296
2025-12-30   6.777755   1.362451  12.849390   0.776327 -0.636903 -1.522161   5.722381   6.934641   8.187143  12.166803  18.094665    0.421186    0.418313    0.381873    0.304318